services:
  n8n-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: n8n-dev
    restart: unless-stopped
    ports:
      - "5678:5678"
    volumes:
      - n8n_dev_data:/home/node/.n8n
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - N8N_EXTERNAL_PACKAGES=/usr/local/lib/node_modules/n8n/node_modules
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_RUNNERS_ENABLED=true
      - NODE_ENV=production
      - TZ=Asia/Tokyo

volumes:
  n8n_dev_data:
    external: true
